using System.Text.Json;
using DreamAirTracking.Core.Bridge;
using DreamAirTracking.Core.Runtime;

namespace DreamAirTracking.Tests.Runtime;

/// <summary>
/// End-to-end golden parity: NeuralEyeRuntime.ProcessPair must reproduce the Python runtime's
/// VRCFT-consumed outputs on the same frame pairs (preprocessing + ONNX + post-processing).
/// Reference generated by scripts/ml/tests/gen_e11_golden_parity.py. Machine-local: reads the
/// fixture path from env var DAT_E11_GOLDEN; skips (no-op) when unset or missing (e.g. CI).
/// </summary>
public sealed class GoldenParityTests
{
    private const double Tol = 2e-3;

    [Fact]
    public void NativeMatchesPythonConsumedFields()
    {
        string? fixturePath = Environment.GetEnvironmentVariable("DAT_E11_GOLDEN");
        if (string.IsNullOrWhiteSpace(fixturePath) || !File.Exists(fixturePath)) return;

        using var doc = JsonDocument.Parse(File.ReadAllText(fixturePath));
        var root = doc.RootElement;
        string mainOnnx = root.GetProperty("main_onnx").GetString()!;
        string exprOnnx = root.GetProperty("expression_onnx").GetString()!;
        if (!File.Exists(mainOnnx)) return;

        var cfg = new NeuralRuntimeConfig
        {
            MainOnnxPath = mainOnnx,
            ExpressionOnnxPath = File.Exists(exprOnnx) ? exprOnnx : null,
            ImageSize = root.GetProperty("image_size").GetInt32(),
            ExpressionImageSize = root.GetProperty("expression_image_size").GetInt32(),
            // all other constants use NeuralRuntimeConfig defaults, which match the generator
        };

        using var runtime = new NeuralEyeRuntime(cfg);

        // rawX/Y and monocularX/Y are DIAGNOSTIC fields (emitted but not consumed by VRCFT).
        // They carry the un-smoothed gaze, which is the most sensitive to sub-LSB JPEG-decoder /
        // resampler pixel differences (ImageSharp vs PIL). Everything else is VRCFT-consumed.
        var diagnosticFields = new HashSet<string> { "rawX", "rawY", "monocularX", "monocularY" };
        double diagMax = 0.0, consumedMax = 0.0;
        string diagWorst = "", consumedWorst = "";
        var fieldMax = new Dictionary<string, double>();
        int frames = 0, i = 0;
        foreach (var f in root.GetProperty("frames").EnumerateArray())
        {
            string lf = f.GetProperty("left_file").GetString()!;
            string rf = f.GetProperty("right_file").GetString()!;
            if (!File.Exists(lf) || !File.Exists(rf)) continue;

            BridgeTrackingState s = runtime.ProcessPair(File.ReadAllBytes(lf), File.ReadAllBytes(rf), i, 0.0);
            i++;
            frames++;

            void Check(string name, double expected, double got)
            {
                double d = Math.Abs(expected - got);
                fieldMax[name] = Math.Max(fieldMax.GetValueOrDefault(name), d);
                if (diagnosticFields.Contains(name))
                {
                    if (d > diagMax) { diagMax = d; diagWorst = $"{name}@frame{frames} exp={expected:F6} got={got:F6}"; }
                }
                else if (d > consumedMax) { consumedMax = d; consumedWorst = $"{name}@frame{frames} exp={expected:F6} got={got:F6}"; }
            }

            Check("normalizedX", f.GetProperty("normalizedX").GetDouble(), s.Left.NormalizedX);
            Check("normalizedY", f.GetProperty("normalizedY").GetDouble(), s.Left.NormalizedY);
            Check("rawX", f.GetProperty("rawX").GetDouble(), s.Left.RawX);
            Check("rawY", f.GetProperty("rawY").GetDouble(), s.Left.RawY);
            Check("monocularX", f.GetProperty("monocularX").GetDouble(), s.Left.MonocularNormalizedX);
            Check("monocularY", f.GetProperty("monocularY").GetDouble(), s.Left.MonocularNormalizedY);
            Check("opennessL", f.GetProperty("opennessL").GetDouble(), s.Left.Openness);
            Check("opennessR", f.GetProperty("opennessR").GetDouble(), s.Right.Openness);
            Check("wideL", f.GetProperty("wideL").GetDouble(), s.Left.Wide);
            Check("wideR", f.GetProperty("wideR").GetDouble(), s.Right.Wide);
            Check("squintL", f.GetProperty("squintL").GetDouble(), s.Left.Squint);
            Check("squintR", f.GetProperty("squintR").GetDouble(), s.Right.Squint);
            Check("pupilNormL", f.GetProperty("pupilNormL").GetDouble(), s.Left.PupilDiameterNormalized);
            Check("pupilNormR", f.GetProperty("pupilNormR").GetDouble(), s.Right.PupilDiameterNormalized);
            Check("pupilExprL", f.GetProperty("pupilExprL").GetDouble(), s.Left.PupilExpressionNormalized);
            Check("pupilExprR", f.GetProperty("pupilExprR").GetDouble(), s.Right.PupilExpressionNormalized);
        }

        Assert.True(frames > 0, "no golden frames were processed (frame files missing?)");
        string breakdown = string.Join(", ", fieldMax.OrderByDescending(kv => kv.Value).Select(kv => $"{kv.Key}={kv.Value:E2}"));
        // VRCFT-consumed fields (smoothed gaze / openness / wide / squint / pupil) must match tightly;
        // openness & pupil are bit-exact, smoothed gaze & expression < 0.5% (EMA absorbs decoder noise).
        Assert.True(consumedMax <= 5e-3, $"consumed-field parity max {consumedMax:E3} over {frames} frames exceeds 5e-3; worst {consumedWorst}\n  per-field: {breakdown}");
        // Diagnostic un-smoothed gaze tolerates ~1% cross-decoder pixel noise (not consumed by VRCFT).
        Assert.True(diagMax <= 1.5e-2, $"diagnostic gaze parity max {diagMax:E3} over {frames} frames exceeds 1.5e-2; worst {diagWorst}\n  per-field: {breakdown}");
    }
}
