using System.Text.Json;
using DreamAirTracking.Core.Runtime;
using DreamAirTracking.Core.Runtime.PostProcess;

namespace DreamAirTracking.Tests.Runtime;

/// <summary>
/// Parity tests: the C# post-processing port must match the Python runtime
/// (predict_live_multitask.py / live_gaze_dry_run.py) within 1e-5 on fixtures
/// generated by scripts/ml/tests/gen_e11_parity_fixtures.py.
/// </summary>
public sealed class PostProcessParityTests
{
    private const double Tol = 1e-5;
    private static readonly JsonElement Fx = LoadFixture();

    private static JsonElement LoadFixture()
    {
        var candidates = new[]
        {
            Path.Combine(AppContext.BaseDirectory, "Runtime", "fixtures", "postprocess_parity.json"),
        };
        string? path = candidates.FirstOrDefault(File.Exists);
        if (path is null)
        {
            // fallback: walk up to repo and read from source tree
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "DreamAirTracking.sln")))
                dir = dir.Parent;
            if (dir is not null)
                path = Path.Combine(dir.FullName, "tests", "DreamAirTracking.Tests", "Runtime", "fixtures", "postprocess_parity.json");
        }
        if (path is null || !File.Exists(path))
            throw new FileNotFoundException("postprocess_parity.json fixture not found; run gen_e11_parity_fixtures.py");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement.Clone();
    }

    private static double[] A(JsonElement e) => e.EnumerateArray().Select(x => x.GetDouble()).ToArray();
    private static Vec2 V(JsonElement e) { var a = A(e); return new Vec2(a[0], a[1]); }
    private static EyePair P(JsonElement e) { var a = A(e); return new EyePair(a[0], a[1]); }
    private static double D(JsonElement e, string k, double def = 0.0) => e.TryGetProperty(k, out var v) ? v.GetDouble() : def;

    private static void Eq(Vec2 exp, Vec2 got, string ctx)
    {
        Assert.True(Math.Abs(exp.X - got.X) <= Tol && Math.Abs(exp.Y - got.Y) <= Tol,
            $"{ctx}: expected ({exp.X},{exp.Y}) got ({got.X},{got.Y})");
    }
    private static void Eq(EyePair exp, EyePair got, string ctx)
    {
        Assert.True(Math.Abs(exp.Left - got.Left) <= Tol && Math.Abs(exp.Right - got.Right) <= Tol,
            $"{ctx}: expected ({exp.Left},{exp.Right}) got ({got.Left},{got.Right})");
    }

    [Fact]
    public void OpennessCurveParity()
    {
        int i = 0;
        foreach (var c in Fx.GetProperty("openness_curve").EnumerateArray())
        {
            var got = OpennessCurve.Apply(P(c.GetProperty("input")), c.GetProperty("mode").GetString()!,
                D(c, "threshold"), D(c, "knee"), D(c, "gamma"));
            Eq(P(c.GetProperty("output")), got, $"openness_curve[{i++}] {c.GetProperty("mode").GetString()}");
        }
    }

    [Fact]
    public void NormalizePerEyeParity()
    {
        int i = 0;
        foreach (var c in Fx.GetProperty("normalize_per_eye").EnumerateArray())
        {
            var got = PerEyeOpennessNormalizer.Normalize(P(c.GetProperty("model")), P(c.GetProperty("open_p95")),
                P(c.GetProperty("closed_p05")), D(c, "min_range", 0.05));
            Eq(P(c.GetProperty("output")), got, $"normalize_per_eye[{i++}]");
        }
    }

    [Fact]
    public void NormalizePerEyeHalfAnchorParity()
    {
        int i = 0;
        foreach (var c in Fx.GetProperty("normalize_per_eye_half").EnumerateArray())
        {
            var got = PerEyeOpennessNormalizer.Normalize(P(c.GetProperty("model")), P(c.GetProperty("open_p95")),
                P(c.GetProperty("closed_p05")), D(c, "min_range", 0.05), P(c.GetProperty("half_p50")));
            Eq(P(c.GetProperty("output")), got, $"normalize_per_eye_half[{i++}]");
        }
    }

    [Fact]
    public void OpennessDualPathParity()
    {
        foreach (var grp in Fx.GetProperty("openness_dual_path").EnumerateArray())
        {
            var dp = new OpennessDualPath();
            double threshold = D(grp, "threshold", 0.90), knee = D(grp, "knee", 0.28), gamma = D(grp, "gamma", 1.25);
            double enter = D(grp, "enter_velocity", 0.06), exit = D(grp, "exit_velocity", 0.02);
            int hold = grp.TryGetProperty("hold_frames", out var h) ? h.GetInt32() : 6;
            int i = 0;
            foreach (var s in grp.GetProperty("steps").EnumerateArray())
            {
                var got = dp.Apply(P(s.GetProperty("input")), threshold, knee, gamma, enter, exit, hold);
                Eq(P(s.GetProperty("output")), got, $"openness_dual_path[{i++}]");
            }
        }
    }

    [Fact]
    public void EyeShapeCurveParity()
    {
        int i = 0;
        foreach (var c in Fx.GetProperty("eye_shape_curve").EnumerateArray())
        {
            var got = EyeShapeCurve.Apply(P(c.GetProperty("values")), D(c, "scale"), D(c, "gamma"), D(c, "deadzone"));
            Eq(P(c.GetProperty("output")), got, $"eye_shape_curve[{i++}]");
        }
    }

    [Fact]
    public void RuntimeMapParity()
    {
        int i = 0;
        foreach (var c in Fx.GetProperty("runtime_map").EnumerateArray())
        {
            var got = RuntimeGazeMap.Apply(V(c.GetProperty("value")), V(c.GetProperty("offset")), V(c.GetProperty("gain")),
                D(c, "clamp"), c.GetProperty("clamp_mode").GetString()!, D(c, "soft_knee"));
            Eq(V(c.GetProperty("output")), got, $"runtime_map[{i++}]");
        }
    }

    [Fact]
    public void UpdateSmoothParity()
    {
        int g = 0;
        foreach (var grp in Fx.GetProperty("update_smooth").EnumerateArray())
        {
            double alpha = D(grp, "alpha"), maxStep = D(grp, "max_step");
            Vec2? prev = null;
            int i = 0;
            foreach (var s in grp.GetProperty("steps").EnumerateArray())
            {
                var got = GazeSmoother.Update(prev, V(s.GetProperty("current")), alpha, maxStep);
                Eq(V(s.GetProperty("output")), got, $"update_smooth[{g}][{i++}]");
                prev = got;
            }
            g++;
        }
    }

    [Fact]
    public void OutputGazeMapperParity()
    {
        int g = 0;
        foreach (var grp in Fx.GetProperty("output_gaze_mapper").EnumerateArray())
        {
            var cfg = grp.GetProperty("config");
            var m = new OutputGazeMapper(
                mode: cfg.GetProperty("mode").GetString()!,
                deadzone: D(cfg, "deadzone", 0.015), gamma: D(cfg, "gamma", 1.0), limit: D(cfg, "limit", 1.0),
                centerRadius: D(cfg, "center_radius", 0.08), centerTau: D(cfg, "center_tau", 6.0),
                centerMaxStep: D(cfg, "center_max_step", 0.025));
            int i = 0;
            foreach (var s in grp.GetProperty("steps").EnumerateArray())
            {
                var got = m.Update(V(s.GetProperty("value")), D(s, "t"), D(s, "conf", 1.0), D(s, "open", 1.0));
                Eq(V(s.GetProperty("output")), got, $"output_gaze_mapper[{g}][{i++}]");
            }
            g++;
        }
    }

    [Fact]
    public void PupilWideParity()
    {
        int g = 0;
        foreach (var grp in Fx.GetProperty("pupil_wide").EnumerateArray())
        {
            var hold = new PupilWideHold();
            double enter = D(grp, "enter"), exit = D(grp, "exit"), ema = D(grp, "ema");
            int frames = grp.GetProperty("hold_frames").GetInt32();
            int i = 0;
            foreach (var s in grp.GetProperty("steps").EnumerateArray())
            {
                var got = hold.Update(P(s.GetProperty("raw")), enter, exit, frames, ema);
                Eq(P(s.GetProperty("output")), got, $"pupil_wide[{g}][{i++}]");
            }
            g++;
        }
    }

    [Fact]
    public void PupilOutputParity()
    {
        int i = 0;
        foreach (var c in Fx.GetProperty("pupil_output").EnumerateArray())
        {
            string modeRaw = c.GetProperty("mode_raw").GetString()!;
            string mode = c.GetProperty("mode").GetString()!;
            Assert.Equal(mode, PupilOutput.NormalizeMode(modeRaw));
            var got = PupilOutput.Compute(mode, D(c, "openness"), D(c, "wide"), D(c, "radius"), D(c, "confidence"));
            var exp = c.GetProperty("output");
            string ctx = $"pupil_output[{i++}] {modeRaw}";
            Assert.True(exp.GetProperty("found").GetBoolean() == got.Found, $"{ctx} found");
            Assert.True(exp.GetProperty("quality").GetBoolean() == got.Quality, $"{ctx} quality");
            Assert.True(Math.Abs(exp.GetProperty("normalized").GetDouble() - got.Normalized) <= Tol, $"{ctx} normalized");
            Assert.True(Math.Abs(exp.GetProperty("expressionNormalized").GetDouble() - got.ExpressionNormalized) <= Tol, $"{ctx} exprNorm");
            Assert.Equal(exp.GetProperty("reason").GetString(), got.Reason);
        }
    }

    [Fact]
    public void TrackingStateMachineParity()
    {
        int g = 0;
        foreach (var grp in Fx.GetProperty("tracking").EnumerateArray())
        {
            var pars = new TrackingStateParams
            {
                OpennessMachine = grp.GetProperty("openness_machine").GetBoolean(),
                GazeHold = grp.GetProperty("gaze_hold").GetBoolean(),
                // P0-3 params (absent in older fixture groups -> legacy defaults)
                CloseConfirmFrames = grp.TryGetProperty("close_confirm_frames", out var ccf) ? ccf.GetInt32() : 0,
                CloseConfirmFloor = D(grp, "close_confirm_floor", 0.22),
                PartialDeadband = D(grp, "partial_deadband", 0.0),
            };
            var m = new TrackingStateMachine(pars);
            int i = 0;
            foreach (var s in grp.GetProperty("steps").EnumerateArray())
            {
                var r = m.Update(P(s.GetProperty("curved")), D(s, "pair_conf"), V(s.GetProperty("gaze")));
                string ctx = $"tracking[{g}][{i++}]";
                Eq(P(s.GetProperty("out_openness")), r.Openness, $"{ctx} openness");
                Eq(V(s.GetProperty("out_gaze")), r.Gaze, $"{ctx} gaze");
                Assert.True(s.GetProperty("state").GetString() == r.State, $"{ctx} state: exp {s.GetProperty("state").GetString()} got {r.State}");
                Assert.Equal(s.GetProperty("left_sub").GetString(), r.LeftSubstate);
                Assert.Equal(s.GetProperty("right_sub").GetString(), r.RightSubstate);
            }
            g++;
        }
    }
}
